In [1]:
# Dependencies
import pandas as pd

In [2]:
# Store filepath in a variable
file_2018 = "Resources/WHR2018Chapter2OnlineData_2018.xls"
file_2017 = "Resources/online-data-chapter-2-whr-2017.xlsx"
file_2016 = "Resources/Online-data-for-chapter-2-whr-2016.xlsx"
file_2015 = "Resources/Chapter2OnlineData_Expanded2015.xlsx"

In [3]:
# Read our Data file with the pandas library
sheet1_2018_df = pd.read_excel(file_2018, 'Table2.1')
sheet2_2018_df = pd.read_excel(file_2018, 'Figure2.2')
sheet2_2016_df = pd.read_excel(file_2016, 'Figure2.2')
sheet2_2017_df = pd.read_excel(file_2017, 'Figure2.2')
sheet2_2015_df = pd.read_excel(file_2015, 'Figure2.2',skiprows=3)

In [4]:
renamed_sheet1_2018 = sheet1_2018_df.rename(columns={"year":"Year","country":"Country"})
renamed_sheet1_2018.head()

,Country,Year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government,Democratic Quality,Delivery Quality,Standard deviation of ladder by country-year,Standard deviation/Mean of ladder by country-year,GINI index (World Bank estimate),"GINI index (World Bank estimate), average 2000-15","gini of household income reported in Gallup, by wp5-year"
0,Afghanistan,2008,3.723590,7.168690,0.450662,49.209663,0.718114,0.181819,0.881686,0.517637,0.258195,0.612072,-1.929690,-1.655084,1.774662,0.476600,NaN,NaN,NaN
1,Afghanistan,2009,4.401778,7.333790,0.552308,49.624432,0.678896,0.203614,0.850035,0.583926,0.237092,0.611545,-2.044093,-1.635025,1.722688,0.391362,NaN,NaN,0.441906
2,Afghanistan,2010,4.758381,7.386629,0.539075,50.008961,0.600127,0.137630,0.706766,0.618265,0.275324,0.299357,-1.991810,-1.617176,1.878622,0.394803,NaN,NaN,0.327318
3,Afghanistan,2011,3.831719,7.415019,0.521104,50.367298,0.495901,0.175329,0.731109,0.611387,0.267175,0.307386,-1.919018,-1.616221,1.785360,0.465942,NaN,NaN,0.336764
4,Afghanistan,2012,3.782938,7.517126,0.520637,50.709263,0.530935,0.247159,0.775620,0.710385,0.267919,0.435440,-1.842996,-1.404078,1.798283,0.475367,NaN,NaN,0.344540

In [5]:
# check data types
renamed_sheet1_2018.dtypes

country                                                      object
year                                                          int64
Life Ladder                                                 float64
Log GDP per capita                                          float64
Social support                                              float64
Healthy life expectancy at birth                            float64
Freedom to make life choices                                float64
Generosity                                                  float64
Perceptions of corruption                                   float64
Positive affect                                             float64
Negative affect                                             float64
Confidence in national government                           float64
Democratic Quality                                          float64
Delivery Quality                                            float64
Standard deviation of ladder by country-year                float64
Standard deviation/Mean of ladder by country-year           float64
GINI index (World Bank estimate)                            float64
GINI index (World Bank estimate), average 2000-15           float64
gini of household income reported in Gallup, by wp5-year    float64
dtype: object

In [6]:
#create series of columns we do not need
sheet2_2018_df.columns.to_series()["Unnamed: 11":"Unnamed: 23"]

Unnamed: 11    Unnamed: 11
Unnamed: 12    Unnamed: 12
Unnamed: 13    Unnamed: 13
Unnamed: 14    Unnamed: 14
Unnamed: 15    Unnamed: 15
Unnamed: 16    Unnamed: 16
Unnamed: 17    Unnamed: 17
Unnamed: 18    Unnamed: 18
Unnamed: 19    Unnamed: 19
Unnamed: 20    Unnamed: 20
Unnamed: 21    Unnamed: 21
Unnamed: 22    Unnamed: 22
Unnamed: 23    Unnamed: 23
dtype: object

In [7]:
#remove columns we do not need
sheet2_2018_df.drop(sheet2_2018_df.columns.to_series()["Unnamed: 11":"Unnamed: 23"], axis=1, inplace=True)
sheet2_2018_df.head()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.6321,7.694913,7.569287,2.595186,1.305095,1.592134,0.874454,0.680633,0.191638,0.392961
1,Norway,7.5937,7.657077,7.530323,2.383242,1.455627,1.582340,0.860763,0.686420,0.285636,0.339687
2,Denmark,7.5553,7.623292,7.487309,2.370179,1.351153,1.590453,0.867933,0.683251,0.284392,0.407917
3,Iceland,7.4952,7.592534,7.397867,2.425990,1.343301,1.644378,0.913802,0.676502,0.353233,0.138019
4,Switzerland,7.4873,7.569994,7.404606,2.319529,1.419727,1.548998,0.927076,0.659779,0.255525,0.356677

In [8]:
sheet2_2016_df.head()

,Country,Happiness score,Whisker-high,Whisker-low,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia (2.33) + residual,Unnamed: 11,Unnamed: 12,Figure 2.2: Ranking of Happiness 2013-2015
0,Denmark,7.526,7.591507,7.460493,1.441784,1.163745,0.795040,0.579413,0.361710,0.444532,2.739390,NaN,NaN,NaN
1,Switzerland,7.509,7.589791,7.428208,1.527334,1.145236,0.863029,0.585572,0.280825,0.412033,2.694632,NaN,NaN,NaN
2,Iceland,7.501,7.669368,7.332632,1.426655,1.183259,0.867333,0.566242,0.476784,0.149747,2.831373,NaN,NaN,NaN
3,Norway,7.498,7.574923,7.421077,1.577440,1.126896,0.795789,0.596086,0.378948,0.357758,2.664645,NaN,NaN,NaN
4,Finland,7.413,7.474935,7.351065,1.405979,1.134640,0.810914,0.571037,0.254919,0.410040,2.825965,NaN,NaN,NaN

In [9]:
#remove columns we do not need
sheet2_2016_df.drop(sheet2_2016_df.columns[12], axis=1, inplace=True)
sheet2_2016_df.head()

,Country,Happiness score,Whisker-high,Whisker-low,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia (2.33) + residual,Unnamed: 11,Figure 2.2: Ranking of Happiness 2013-2015
0,Denmark,7.526,7.591507,7.460493,1.441784,1.163745,0.795040,0.579413,0.361710,0.444532,2.739390,NaN,NaN
1,Switzerland,7.509,7.589791,7.428208,1.527334,1.145236,0.863029,0.585572,0.280825,0.412033,2.694632,NaN,NaN
2,Iceland,7.501,7.669368,7.332632,1.426655,1.183259,0.867333,0.566242,0.476784,0.149747,2.831373,NaN,NaN
3,Norway,7.498,7.574923,7.421077,1.577440,1.126896,0.795789,0.596086,0.378948,0.357758,2.664645,NaN,NaN
4,Finland,7.413,7.474935,7.351065,1.405979,1.134640,0.810914,0.571037,0.254919,0.410040,2.825965,NaN,NaN

In [10]:
#remove columns we do not need
sheet2_2016_df.drop(sheet2_2016_df.columns[11], axis=1, inplace=True)
sheet2_2016_df.head()

,Country,Happiness score,Whisker-high,Whisker-low,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia (2.33) + residual,Figure 2.2: Ranking of Happiness 2013-2015
0,Denmark,7.526,7.591507,7.460493,1.441784,1.163745,0.795040,0.579413,0.361710,0.444532,2.739390,NaN
1,Switzerland,7.509,7.589791,7.428208,1.527334,1.145236,0.863029,0.585572,0.280825,0.412033,2.694632,NaN
2,Iceland,7.501,7.669368,7.332632,1.426655,1.183259,0.867333,0.566242,0.476784,0.149747,2.831373,NaN
3,Norway,7.498,7.574923,7.421077,1.577440,1.126896,0.795789,0.596086,0.378948,0.357758,2.664645,NaN
4,Finland,7.413,7.474935,7.351065,1.405979,1.134640,0.810914,0.571037,0.254919,0.410040,2.825965,NaN

In [11]:
sheet2_2017_df.head()

,Country,Happiness score,Whisker-high,Whisker-low,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia (1.85) + residual
0,Norway,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [12]:
# Using .rename(columns={}) in order to rename columns
renamed_2016 = sheet2_2016_df.rename(columns={"Dystopia (2.33) + residual":"Dystopia Residual"})
renamed_2016.head()

,Country,Happiness score,Whisker-high,Whisker-low,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia Residual,Figure 2.2: Ranking of Happiness 2013-2015
0,Denmark,7.526,7.591507,7.460493,1.441784,1.163745,0.795040,0.579413,0.361710,0.444532,2.739390,NaN
1,Switzerland,7.509,7.589791,7.428208,1.527334,1.145236,0.863029,0.585572,0.280825,0.412033,2.694632,NaN
2,Iceland,7.501,7.669368,7.332632,1.426655,1.183259,0.867333,0.566242,0.476784,0.149747,2.831373,NaN
3,Norway,7.498,7.574923,7.421077,1.577440,1.126896,0.795789,0.596086,0.378948,0.357758,2.664645,NaN
4,Finland,7.413,7.474935,7.351065,1.405979,1.134640,0.810914,0.571037,0.254919,0.410040,2.825965,NaN

In [13]:
renamed_2017 = sheet2_2017_df.rename(columns={"Dystopia (1.85) + residual":"Dystopia Residual"})
renamed_2017.head()

,Country,Happiness score,Whisker-high,Whisker-low,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia Residual
0,Norway,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [14]:
renamed_2018 = sheet2_2018_df.rename(columns={"Dystopia (1.92) + residual":"Dystopia Residual"})
renamed_2018.head()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia Residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.6321,7.694913,7.569287,2.595186,1.305095,1.592134,0.874454,0.680633,0.191638,0.392961
1,Norway,7.5937,7.657077,7.530323,2.383242,1.455627,1.582340,0.860763,0.686420,0.285636,0.339687
2,Denmark,7.5553,7.623292,7.487309,2.370179,1.351153,1.590453,0.867933,0.683251,0.284392,0.407917
3,Iceland,7.4952,7.592534,7.397867,2.425990,1.343301,1.644378,0.913802,0.676502,0.353233,0.138019
4,Switzerland,7.4873,7.569994,7.404606,2.319529,1.419727,1.548998,0.927076,0.659779,0.255525,0.356677

In [15]:
#add year
renamed_2018["Year"] = 2018
renamed_2017["Year"] = 2017
renamed_2016["Year"] = 2016
sheet2_2015_df["Year"] = 2015

In [19]:
#remove rows of data before 2016
cleansheet1_2018 = renamed_sheet1_2018[renamed_sheet1_2018.Year>=2016]
cleansheet1_2018.head()

,Country,Year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government,Democratic Quality,Delivery Quality,Standard deviation of ladder by country-year,Standard deviation/Mean of ladder by country-year,GINI index (World Bank estimate),"GINI index (World Bank estimate), average 2000-15","gini of household income reported in Gallup, by wp5-year"
8,Afghanistan,2016,4.220169,7.461401,0.559072,52.016529,0.522566,0.057072,0.793246,0.564953,0.348332,0.324990,-1.917693,-1.432548,1.796219,0.425627,NaN,NaN,0.418629
9,Afghanistan,2017,2.661718,7.460144,0.490880,52.339527,0.427011,-0.106340,0.954393,0.496349,0.371326,0.261179,NaN,NaN,1.454051,0.546283,NaN,NaN,0.286599
18,Albania,2016,4.511101,9.337774,0.638411,68.871811,0.729819,-0.023276,0.901071,0.675244,0.321706,0.400910,0.208456,-0.139161,2.646668,0.586701,NaN,0.30325,0.416540
19,Albania,2017,4.639548,9.373718,0.637698,69.051659,0.749611,-0.035140,0.876135,0.669241,0.333884,0.457738,NaN,NaN,2.682105,0.578096,NaN,0.30325,0.410488
24,Algeria,2016,5.340854,9.541166,0.748588,65.509514,NaN,NaN,NaN,0.660510,0.377112,NaN,-1.008262,-0.814304,2.114553,0.395920,NaN,0.27600,0.604617

In [20]:
sheet2_2015_df.head()

,WP5 Country,country,Regional indicator,Ladder score,Standard error of ladder score,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,...,Democratic Quality 2012,Delivery Quality 2012,"Most people can be trusted, Gallup, mostly 2009-10","Most people can be trusted, WVS round 1981-1984","Most people can be trusted, WVS round 1989-1993","Most people can be trusted, WVS round 1994-1998","Most people can be trusted, WVS round 1999-2004","Most people can be trusted, WVS round 2005-2009","Most people can be trusted, WVS round 2010-2014",Year
0,184 Switzerland,Switzerland,Western Europe,7.587,0.034112,10.857283,0.953136,72.736862,0.947724,0.080692,...,1.534588,1.876428,0.437882,NaN,0.265255,0.378479,NaN,0.518936,NaN,2015
1,130 Iceland,Iceland,Western Europe,7.561,0.048836,10.568534,0.975240,72.968559,0.912811,0.257895,...,1.337266,1.521620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
2,025 Denmark,Denmark,Western Europe,7.527,0.033283,10.639521,0.957780,70.323395,0.932365,0.137351,...,1.299623,2.000511,0.667515,NaN,NaN,NaN,NaN,NaN,NaN,2015
3,160 Norway,Norway,Western Europe,7.522,0.038802,11.048872,0.945359,70.705254,0.951669,0.144468,...,1.531618,1.903925,NaN,NaN,NaN,0.647737,NaN,0.737305,NaN,2015
4,046 Canada,Canada,North America and ANZ,7.427,0.035526,10.642016,0.941860,71.443192,0.916792,0.285598,...,1.268314,1.780549,0.450844,NaN,NaN,NaN,0.385469,0.418500,NaN,2015

In [21]:
#create happiness score for 2015
sheet2_2015_df["Happiness score"] = sheet2_2015_df["Explained by: Log GDP per capita"]+sheet2_2015_df["Explained by: Social support"]+\
sheet2_2015_df["Explained by: Healthy life expectancy"]+sheet2_2015_df["Explained by: Freedom to make life choices"]+\
sheet2_2015_df["Explained by: Generosity"]+sheet2_2015_df["Explained by: Perceptions of corruption"]
sheet2_2015_df.head()

,WP5 Country,country,Regional indicator,Ladder score,Standard error of ladder score,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,...,Delivery Quality 2012,"Most people can be trusted, Gallup, mostly 2009-10","Most people can be trusted, WVS round 1981-1984","Most people can be trusted, WVS round 1989-1993","Most people can be trusted, WVS round 1994-1998","Most people can be trusted, WVS round 1999-2004","Most people can be trusted, WVS round 2005-2009","Most people can be trusted, WVS round 2010-2014",Year,Happiness score
0,184 Switzerland,Switzerland,Western Europe,7.587,0.034112,10.857283,0.953136,72.736862,0.947724,0.080692,...,1.876428,0.437882,NaN,0.265255,0.378479,NaN,0.518936,NaN,2015,5.069568
1,130 Iceland,Iceland,Western Europe,7.561,0.048836,10.568534,0.975240,72.968559,0.912811,0.257895,...,1.521620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015,4.858919
2,025 Denmark,Denmark,Western Europe,7.527,0.033283,10.639521,0.957780,70.323395,0.932365,0.137351,...,2.000511,0.667515,NaN,NaN,NaN,NaN,NaN,NaN,2015,5.035043
3,160 Norway,Norway,Western Europe,7.522,0.038802,11.048872,0.945359,70.705254,0.951669,0.144468,...,1.903925,NaN,NaN,NaN,0.647737,NaN,0.737305,NaN,2015,5.056915
4,046 Canada,Canada,North America and ANZ,7.427,0.035526,10.642016,0.941860,71.443192,0.916792,0.285598,...,1.780549,0.450844,NaN,NaN,NaN,0.385469,0.418500,NaN,2015,4.975180

In [22]:
#rename column Country
renamed_2015 = sheet2_2015_df.rename(columns={"country":"Country", "Explained by: Log GDP per capita":"Explained by: GDP per capita"})
renamed_2015.head()

,WP5 Country,Country,Regional indicator,Ladder score,Standard error of ladder score,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,...,Delivery Quality 2012,"Most people can be trusted, Gallup, mostly 2009-10","Most people can be trusted, WVS round 1981-1984","Most people can be trusted, WVS round 1989-1993","Most people can be trusted, WVS round 1994-1998","Most people can be trusted, WVS round 1999-2004","Most people can be trusted, WVS round 2005-2009","Most people can be trusted, WVS round 2010-2014",Year,Happiness score
0,184 Switzerland,Switzerland,Western Europe,7.587,0.034112,10.857283,0.953136,72.736862,0.947724,0.080692,...,1.876428,0.437882,NaN,0.265255,0.378479,NaN,0.518936,NaN,2015,5.069568
1,130 Iceland,Iceland,Western Europe,7.561,0.048836,10.568534,0.975240,72.968559,0.912811,0.257895,...,1.521620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015,4.858919
2,025 Denmark,Denmark,Western Europe,7.527,0.033283,10.639521,0.957780,70.323395,0.932365,0.137351,...,2.000511,0.667515,NaN,NaN,NaN,NaN,NaN,NaN,2015,5.035043
3,160 Norway,Norway,Western Europe,7.522,0.038802,11.048872,0.945359,70.705254,0.951669,0.144468,...,1.903925,NaN,NaN,NaN,0.647737,NaN,0.737305,NaN,2015,5.056915
4,046 Canada,Canada,North America and ANZ,7.427,0.035526,10.642016,0.941860,71.443192,0.916792,0.285598,...,1.780549,0.450844,NaN,NaN,NaN,0.385469,0.418500,NaN,2015,4.975180

In [23]:
renamed_2016.columns

Index(['Country', 'Happiness score', 'Whisker-high', 'Whisker-low',
       'Explained by: GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia Residual', 'Figure 2.2: Ranking of Happiness 2013-2015',
       'Year'],
      dtype='object')

In [24]:
renamed_2015.columns

Index(['WP5 Country', 'Country', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'Logged GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Dystopia + residual', 'Explained by: GDP per capita',
       'Explained by: Social support', 'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Trust in national government', 'Democratic Quality 2012',
       'Delivery Quality 2012',
       'Most people can be trusted, Gallup, mostly 2009-10',
       'Most people can be trusted, WVS round 1981-1984',
       'Most people can be trusted, WVS round 1989-1993',
       'Most people can be trusted, WVS round 1994-1998',
       'Most people can be trusted, WVS round 1999-2004',
       'Most people can be trusted, WVS round 2005-2009',
       'Most people can be trusted, WVS round 2010-2014', 'Year',
       'Happiness score'],
      dtype='object')

In [25]:
cleaned_2015 = renamed_2015[['Country', 'Happiness score', 
       'Explained by: GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Year']]
cleaned_2015.head()

,Country,Happiness score,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Year
0,Switzerland,5.069568,1.396505,1.349505,0.941432,0.665573,0.296775,0.419777,2015
1,Iceland,4.858919,1.302324,1.402231,0.947844,0.628772,0.436297,0.141451,2015
2,Denmark,5.035043,1.325478,1.360581,0.874641,0.649384,0.341386,0.483573,2015
3,Norway,5.056915,1.458997,1.330955,0.885209,0.669732,0.346989,0.365034,2015
4,Canada,4.975180,1.326292,1.322608,0.905631,0.632968,0.458109,0.329573,2015

In [26]:
#Concatenate
happiness_df = [renamed_2018,renamed_2017, renamed_2016, cleaned_2015]
concat_df = pd.concat(happiness_df)
concat_df

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until

,Country,Dystopia Residual,Explained by: Freedom to make life choices,Explained by: GDP per capita,Explained by: Generosity,Explained by: Healthy life expectancy,Explained by: Perceptions of corruption,Explained by: Social support,Figure 2.2: Ranking of Happiness 2013-2015,Happiness score,Whisker-high,Whisker-low,Year
0,Finland,2.595186,0.680633,1.305095,0.191638,0.874454,0.392961,1.592134,NaN,7.632100,7.694913,7.569287,2018
1,Norway,2.383242,0.686420,1.455627,0.285636,0.860763,0.339687,1.582340,NaN,7.593700,7.657077,7.530323,2018
2,Denmark,2.370179,0.683251,1.351153,0.284392,0.867933,0.407917,1.590453,NaN,7.555300,7.623292,7.487309,2018
3,Iceland,2.425990,0.676502,1.343301,0.353233,0.913802,0.138019,1.644378,NaN,7.495200,7.592534,7.397867,2018
4,Switzerland,2.319529,0.659779,1.419727,0.255525,0.927076,0.356677,1.548998,NaN,7.487300,7.569994,7.404606,2018
5,Netherlands,2.448425,0.638065,1.360909,0.333358,0.877710,0.294595,1.488277,NaN,7.441300,7.498353,7.384247,2018
6,Canada,2.305750,0.653067,1.330412,0.320637,0.895846,0.290907,1.531910,NaN,7.328500,7.420735,7.236264,2018
7,New Zealand,2.156168,0.668867,1.268016,0.365170,0.876076,0.388840,1.600625,NaN,7.323800,7.400652,7.246948,2018
8,Sweden,2.216858,0.659404,1.355439,0.284668,0.913462,0.383212,1.501481,NaN,7.314500,7.388290,7.240710,2018
9,Australia,2.139236,0.646526,1.339951,0.361005,0.910445,0.302352,1.572536,NaN,7.272100,7.358463,7.185737,2018
10,Israel,2.816727,0.464048,1.243824,0.262456,0.888351,0.081683,1.432910,NaN,7.190000,7.256923,7.123078,2018
11,Austria,2.319478,0.617242,1.341352,0.242011,0.891358,0.223820,1.504102,NaN,7.139400,7.209448,7.069352,2018
12,Costa Rica,2.910542,0.631519,1.010086,0.143299,0.816699,0.100614,1.458894,NaN,7.071700,7.159923,6.983478,2018
13,Ireland,1.844298,0.613965,1.447582,0.306510,0.876285,0.305819,1.582635,NaN,6.977100,7.054669,6.899531,2018
14,Germany,2.150757,0.586155,1.339620,0.273495,0.860525,0.279843,1.474353,NaN,6.964700,7.024296,6.905105,2018
15,Belgium,2.215041,0.582693,1.323522,0.188035,0.894325,0.240393,1.482876,NaN,6.926900,6.994950,6.858850,2018
16,Luxembourg,1.768551,0.632020,1.576079,0.196052,0.896179,0.320992,1.520071,NaN,6.909900,6.975321,6.844479,2018
17,United States,2.227151,0.547318,1.398043,0.290589,0.818962,0.133434,1.470543,NaN,6.886000,6.974492,6.797509,2018
18,United Kingdom,1.912006,0.532673,1.301310,0.354326,0.883212,0.272071,1.558733,NaN,6.814300,6.887426,6.741174,2018
19,United Arab Emirates,2.095860,0.669838,1.467125,0.283918,0.776146,0.185626,1.295556,NaN,6.774100,6.844495,6.703705,2018
20,Czech Republic,2.493796,0.542642,1.233468,0.063967,0.854076,0.033637,1.489318,NaN,6.710900,6.782628,6.639172,2018
21,Malta,1.783752,0.645339,1.270201,0.375808,0.884367,0.142247,1.524896,NaN,6.626600,6.709103,6.544097,2018
22,France,2.027753,0.520306,1.292785,0.097838,0.908495,0.175691,1.466446,NaN,6.489300,6.568618,6.409981,2018
23,Mexico,2.794510,0.479181,1.038235,0.068684,0.760663,0.094704,1.252233,NaN,6.488200,6.580779,6.395621,2018
24,Chile,2.516591,0.431230,1.131305,0.197056,0.808375,0.060611,1.331021,NaN,6.476200,6.564831,6.387569,2018
25,Taiwan Province of China,2.136127,0.417559,1.365053,0.150619,0.857375,0.077859,1.435968,NaN,6.440600,6.524781,6.356419,2018
26,Panama,2.336180,0.596867,1.112200,0.124510,0.758800,0.063091,1.438390,NaN,6.430000,6.538918,6.321082,2018
27,Brazil,2.592026,0.493464,0.985896,0.110258,0.675138,0.087803,1.474306,NaN,6.418900,6.515156,6.322644,2018
28,Argentina,2.418201,0.569710,1.072671,0.061942,0.743585,0.053507,1.468341,NaN,6.388000,6.485014,6.290986,2018
29,Guatemala,2.870719,0.604298,0.781325,0.178807,0.608414,0.070614,1.267676,NaN,6.381900,6.496899,6.266900,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,Myanmar,NaN,0.440171,0.271075,0.795885,0.482462,0.190335,0.709050,NaN,2.888979,NaN,NaN,2015
129,Georgia,NaN,0.405774,0.741899,0.055467,0.729264,0.383307,0.385619,NaN,2.701330,NaN,NaN,2015
130,Malawi,NaN,0.430537,0.016037,0.331278,0.225619,0.069770,0.411339,NaN,1.484579,NaN,NaN,2015
131,Sri Lanka,NaN,0.537262,0.835237,0.408277,0.708063,0.091785,1.019052,NaN,3.599676,NaN,NaN,2015
132,Cameroon,NaN,0.493090,0.422500,0.206181,0.234024,0.057857,0.887671,NaN,2.301322,NaN,NaN,2015
133,Bulgaria,NaN,0.305870,1.012156,0.119211,0.766490,0.008721,1.106139,NaN,3.318587,NaN,NaN,2015
134,Egypt,NaN,0.172880,0.881796,0.112907,0.617119,0.063245,0.747000,NaN,2.594946,NaN,NaN,2015
135,Yemen,NaN,0.355708,0.546492,0.091314,0.400644,0.078543,0.680929,NaN,2.153630,NaN,NaN,2015
136,Angola,NaN,0.103843,0.757785,0.123438,0.166827,0.071216,0.860398,NaN,2.083507,NaN,NaN,2015
137,Mali,NaN,0.388575,0.260745,0.187982,0.205829,0.123517,1.035262,NaN,2.201911,NaN,NaN,2015
138,Congo (Brazzaville),NaN,0.414661,0.678661,0.123883,0.310509,0.116855,0.662895,NaN,2.307466,NaN,NaN,2015
139,Comoros,NaN,0.229166,0.239057,0.174410,0.363151,0.199003,0.792732,NaN,1.997519,NaN,NaN,2015
140,Uganda,NaN,0.457274,0.211023,0.290663,0.338613,0.072667,1.132986,NaN,2.503226,NaN,NaN,2015
141,Senegal,NaN,0.367719,0.364975,0.208425,0.435401,0.107133,0.976186,NaN,2.459840,NaN,NaN,2015
142,Gabon,NaN,0.319145,1.060235,0.068216,0.433722,0.110907,0.905277,NaN,2.897502,NaN,NaN,2015
143,Niger,NaN,0.476916,0.069399,0.193866,0.297071,0.156392,0.772648,NaN,1.966291,NaN,NaN,2015
144,Cambodia,NaN,0.662456,0.460380,0.403591,0.611138,0.072471,0.627356,NaN,2.837392,NaN,NaN,2015
145,Tanzania,NaN,0.328780,0.285199,0.343773,0.382152,0.057467,1.002677,NaN,2.400048,NaN,NaN,2015
146,Madagascar,NaN,0.191839,0.208245,0.213333,0.467209,0.081239,0.668013,NaN,1.829878,NaN,NaN,2015
147,Central African Republic,NaN,0.488795,0.078501,0.238349,0.066992,0.082893,0.000000,NaN,0.955530,NaN,NaN,2015
148,Chad,NaN,0.235006,0.341929,0.183862,0.150100,0.052687,0.760618,NaN,1.724202,NaN,NaN,2015
149,Guinea,NaN,0.377253,0.174167,0.286567,0.240090,0.121389,0.464750,NaN,1.664216,NaN,NaN,2015
150,Ivory Coast,NaN,0.468659,0.465344,0.201651,0.151850,0.179216,0.771150,NaN,2.237871,NaN,NaN,2015
151,Burkina Faso,NaN,0.394925,0.258115,0.217466,0.271246,0.128320,0.851884,NaN,2.121956,NaN,NaN,2015
152,Afghanistan,NaN,0.234138,0.319821,0.365104,0.303354,0.097188,0.302853,NaN,1.622458,NaN,NaN,2015
153,Rwanda,NaN,0.592007,0.222078,0.226279,0.428643,0.551911,0.773701,NaN,2.794620,NaN,NaN,2015
154,Benin,NaN,0.484496,0.286655,0.182600,0.319098,0.080100,0.353862,NaN,1.706811,NaN,NaN,2015
155,Syria,NaN,0.156841,0.663199,0.471790,0.721932,0.189060,0.474890,NaN,2.677711,NaN,NaN,2015
156,Burundi,NaN,0.118496,0.015303,0.197269,0.223961,0.100620,0.415867,NaN,1.071516,NaN,NaN,2015
157,Togo,NaN,0.364528,0.208676,0.166809,0.284430,0.107313,0.139945,NaN,1.271701,NaN,NaN,2015

In [28]:
cleaned_happiness_df = concat_df[['Country', 'Happiness score', 
       'Explained by: GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Year']]
cleaned_happiness_df.head()

,Country,Happiness score,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Year
0,Finland,7.6321,1.305095,1.592134,0.874454,0.680633,0.191638,0.392961,2018
1,Norway,7.5937,1.455627,1.582340,0.860763,0.686420,0.285636,0.339687,2018
2,Denmark,7.5553,1.351153,1.590453,0.867933,0.683251,0.284392,0.407917,2018
3,Iceland,7.4952,1.343301,1.644378,0.913802,0.676502,0.353233,0.138019,2018
4,Switzerland,7.4873,1.419727,1.548998,0.927076,0.659779,0.255525,0.356677,2018

In [36]:
# Combine the data into a single dataset
complete_df = pd.merge(cleaned_happiness_df, cleansheet1_2018, how="left", on=["Country", "Country","Year","Year"])
complete_df

,Country,Happiness score,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Year,Life Ladder,...,Positive affect,Negative affect,Confidence in national government,Democratic Quality,Delivery Quality,Standard deviation of ladder by country-year,Standard deviation/Mean of ladder by country-year,GINI index (World Bank estimate),"GINI index (World Bank estimate), average 2000-15","gini of household income reported in Gallup, by wp5-year"
0,Finland,7.632100,1.305095,1.592134,0.874454,0.680633,0.191638,0.392961,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Norway,7.593700,1.455627,1.582340,0.860763,0.686420,0.285636,0.339687,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Denmark,7.555300,1.351153,1.590453,0.867933,0.683251,0.284392,0.407917,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Iceland,7.495200,1.343301,1.644378,0.913802,0.676502,0.353233,0.138019,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Switzerland,7.487300,1.419727,1.548998,0.927076,0.659779,0.255525,0.356677,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Netherlands,7.441300,1.360909,1.488277,0.877710,0.638065,0.333358,0.294595,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Canada,7.328500,1.330412,1.531910,0.895846,0.653067,0.320637,0.290907,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,New Zealand,7.323800,1.268016,1.600625,0.876076,0.668867,0.365170,0.388840,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Sweden,7.314500,1.355439,1.501481,0.913462,0.659404,0.284668,0.383212,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Australia,7.272100,1.339951,1.572536,0.910445,0.646526,0.361005,0.302352,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Israel,7.190000,1.243824,1.432910,0.888351,0.464048,0.262456,0.081683,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Austria,7.139400,1.341352,1.504102,0.891358,0.617242,0.242011,0.223820,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Costa Rica,7.071700,1.010086,1.458894,0.816699,0.631519,0.143299,0.100614,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Ireland,6.977100,1.447582,1.582635,0.876285,0.613965,0.306510,0.305819,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Germany,6.964700,1.339620,1.474353,0.860525,0.586155,0.273495,0.279843,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Belgium,6.926900,1.323522,1.482876,0.894325,0.582693,0.188035,0.240393,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Luxembourg,6.909900,1.576079,1.520071,0.896179,0.632020,0.196052,0.320992,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,United States,6.886000,1.398043,1.470543,0.818962,0.547318,0.290589,0.133434,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,United Kingdom,6.814300,1.301310,1.558733,0.883212,0.532673,0.354326,0.272071,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,United Arab Emirates,6.774100,1.467125,1.295556,0.776146,0.669838,0.283918,0.185626,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Czech Republic,6.710900,1.233468,1.489318,0.854076,0.542642,0.063967,0.033637,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Malta,6.626600,1.270201,1.524896,0.884367,0.645339,0.375808,0.142247,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,France,6.489300,1.292785,1.466446,0.908495,0.520306,0.097838,0.175691,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Mexico,6.488200,1.038235,1.252233,0.760663,0.479181,0.068684,0.094704,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Chile,6.476200,1.131305,1.331021,0.808375,0.431230,0.197056,0.060611,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Taiwan Province of China,6.440600,1.365053,1.435968,0.857375,0.417559,0.150619,0.077859,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Panama,6.430000,1.112200,1.438390,0.758800,0.596867,0.124510,0.063091,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Brazil,6.418900,0.985896,1.474306,0.675138,0.493464,0.110258,0.087803,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Argentina,6.388000,1.072671,1.468341,0.743585,0.569710,0.061942,0.053507,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Guatemala,6.381900,0.781325,1.267676,0.608414,0.604298,0.178807,0.070614,2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
597,Myanmar,2.888979,0.271075,0.709050,0.482462,0.440171,0.795885,0.190335,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
598,Georgia,2.701330,0.741899,0.385619,0.729264,0.405774,0.055467,0.383307,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
599,Malawi,1.484579,0.016037,0.411339,0.225619,0.430537,0.331278,0.069770,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
600,Sri Lanka,3.599676,0.835237,1.019052,0.708063,0.537262,0.408277,0.091785,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
601,Cameroon,2.301322,0.422500,0.887671,0.234024,0.493090,0.206181,0.057857,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
602,Bulgaria,3.318587,1.012156,1.106139,0.766490,0.305870,0.119211,0.008721,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
603,Egypt,2.594946,0.881796,0.747000,0.617119,0.172880,0.112907,0.063245,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
604,Yemen,2.153630,0.546492,0.680929,0.400644,0.355708,0.091314,0.078543,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605,Angola,2.083507,0.757785,0.860398,0.166827,0.103843,0.123438,0.071216,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
606,Mali,2.201911,0.260745,1.035262,0.205829,0.388575,0.187982,0.123517,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,Congo (Brazzaville),2.307466,0.678661,0.662895,0.310509,0.414661,0.123883,0.116855,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,Comoros,1.997519,0.239057,0.792732,0.363151,0.229166,0.174410,0.199003,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
609,Uganda,2.503226,0.211023,1.132986,0.338613,0.457274,0.290663,0.072667,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,Senegal,2.459840,0.364975,0.976186,0.435401,0.367719,0.208425,0.107133,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
611,Gabon,2.897502,1.060235,0.905277,0.433722,0.319145,0.068216,0.110907,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
612,Niger,1.966291,0.069399,0.772648,0.297071,0.476916,0.193866,0.156392,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
613,Cambodia,2.837392,0.460380,0.627356,0.611138,0.662456,0.403591,0.072471,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
614,Tanzania,2.400048,0.285199,1.002677,0.382152,0.328780,0.343773,0.057467,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615,Madagascar,1.829878,0.208245,0.668013,0.467209,0.191839,0.213333,0.081239,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
616,Central African Republic,0.955530,0.078501,0.000000,0.066992,0.488795,0.238349,0.082893,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
617,Chad,1.724202,0.341929,0.760618,0.150100,0.235006,0.183862,0.052687,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
618,Guinea,1.664216,0.174167,0.464750,0.240090,0.377253,0.286567,0.121389,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
619,Ivory Coast,2.237871,0.465344,0.771150,0.151850,0.468659,0.201651,0.179216,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
620,Burkina Faso,2.121956,0.258115,0.851884,0.271246,0.394925,0.217466,0.128320,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
621,Afghanistan,1.622458,0.319821,0.302853,0.303354,0.234138,0.365104,0.097188,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
622,Rwanda,2.794620,0.222078,0.773701,0.428643,0.592007,0.226279,0.551911,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
623,Benin,1.706811,0.286655,0.353862,0.319098,0.484496,0.182600,0.080100,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
624,Syria,2.677711,0.663199,0.474890,0.721932,0.156841,0.471790,0.189060,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
625,Burundi,1.071516,0.015303,0.415867,0.223961,0.118496,0.197269,0.100620,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
626,Togo,1.271701,0.208676,0.139945,0.284430,0.364528,0.166809,0.107313,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN